# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom18/rom18.xci
# IP: The module: 'rom18' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom18/rom18_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom18'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom18/rom18.xci
# IP: The module: 'rom18' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom18/rom18_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom18'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
