# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.runs/synth_1/qc_encoder.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k420tiffg901-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.cache/wt [current_project]
set_property parent.project_path C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H1.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H2.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H3.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H4.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H5.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H6.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H7.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H8.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H9.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H10.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H11.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H12.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H13.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H14.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H15.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H16.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H17.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H18.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H19.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H20.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H21.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H22.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H23.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H24.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H25.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H26.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/H27.coe
add_files C:/Work/Codes/Realtime/encode_ru_wd/MATLABFiles/PRBS.coe
read_verilog -library xil_defaultlib -sv {
  C:/Work/Codes/Realtime/encode_ru_wd/rtl/G_row.sv
  C:/Work/Codes/Realtime/encode_ru_wd/rtl/encode.sv
  C:/Work/Codes/Realtime/encode_ru_wd/rtl/qc_encoder.sv
}
read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom1/rom1.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom1/rom1_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom2/rom2.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom2/rom2_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom3/rom3.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom3/rom3_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom4/rom4.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom4/rom4_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom5/rom5.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom5/rom5_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom6/rom6.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom6/rom6_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom7/rom7.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom7/rom7_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom8/rom8.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom8/rom8_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom9/rom9.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom9/rom9_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom10/rom10.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom10/rom10_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom11/rom11.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom11/rom11_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom12/rom12.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom12/rom12_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom13/rom13.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom13/rom13_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom14/rom14.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom14/rom14_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom15/rom15.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom15/rom15_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom16/rom16.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom16/rom16_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom17/rom17.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom17/rom17_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom18/rom18.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom18/rom18_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom19/rom19.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom19/rom19_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom20/rom20.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom20/rom20_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom21/rom21.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom21/rom21_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom22/rom22.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom22/rom22_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom23/rom23.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom23/rom23_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom24/rom24.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom24/rom24_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom25/rom25.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom25/rom25_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom26/rom26.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom26/rom26_ooc.xdc]

read_ip -quiet C:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.srcs/sources_1/ip/rom27/rom27.xci
set_property used_in_implementation false [get_files -all c:/Work/Codes/Realtime/encode_ru_wd/ldpc_ru_encoder/ldpc_ru_encoder.gen/sources_1/ip/rom27/rom27_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top qc_encoder -part xc7k420tiffg901-2L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef qc_encoder.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file qc_encoder_utilization_synth.rpt -pb qc_encoder_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
